WITH RECURSIVE HOURS AS (
   SELECT 0 AS HOUR
   UNION ALL
   SELECT HOUR + 1
   FROM HOURS
   WHERE HOUR < 23
)
SELECT H.HOUR, COALESCE(COUNT(A.DATETIME), 0) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;