SELECT 
   COUNT(FI.ID) AS FISH_COUNT, 
   FNI.FISH_NAME
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
GROUP BY 
   FI.FISH_TYPE,
   FNI.FISH_NAME
ORDER BY FISH_COUNT DESC;