WITH SCORES AS (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT 
    S.TOTAL_SCORE AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM SCORES S
JOIN HR_EMPLOYEES E ON S.EMP_NO = E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;