
SELECT 
CASE
    WHEN A.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') > 0 AND A.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 THEN 'A'
    WHEN A.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#') > 0 THEN 'B'
    WHEN A.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 THEN 'C'
    ELSE NULL
END AS GRADE, ID, EMAIL
FROM DEVELOPERS A
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;


-- 코드를 작성해주세요


WITH SKILL_INFO AS (
   SELECT 
       SUM(CASE WHEN NAME = 'Python' THEN CODE END) AS PYTHON,
       SUM(CASE WHEN NAME = 'C#' THEN CODE END) AS CSHARP,
       SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE END) AS FRONTEND
   FROM SKILLCODES
)
SELECT 
   CASE
       WHEN A.SKILL_CODE & PYTHON > 0 AND A.SKILL_CODE & FRONTEND > 0 THEN 'A'
       WHEN A.SKILL_CODE & CSHARP > 0 THEN 'B'
       WHEN A.SKILL_CODE & FRONTEND > 0 THEN 'C'
   END AS GRADE,
   ID, 
   EMAIL
FROM DEVELOPERS A, SKILL_INFO
WHERE A.SKILL_CODE & (PYTHON + CSHARP + FRONTEND) > 0
ORDER BY GRADE, ID;