SELECT DISTINCT
    ID, EMAIL, FIRST_NAME, LAST_NAME
FROM
    DEVELOPERS AS D
WHERE
    D.SKILL_CODE & (SELECT 'CODE' FROM SKILLCODES WHERE NAME = 'Python')
    OR D.SKILL_CODE & (SELECT 'CODE' FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY
    ID;